version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-posgrado
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: posgrado
      MYSQL_DATABASE: db_posgrado
    command: --default-authentication-plugin=mysql_native_password