package com.service.MsTramiteTesis.model.enums;

public enum TipoEvento {
    PROYECTO_CREADO,
    PROYECTO_MODIFICADO,
    PROYECTO_APROBADO_COORDINADOR,
    PROYECTO_RECHAZADO_COORDINADOR,

    ASESOR_ASIGNADO,
    ASESOR_MODIFICADO,

    REVISION_ASESOR_APROBADA,
    REVISION_ASESOR_OBSERVADA,
    REVISION_JURADO_APROBADA,
    REVISION_JURADO_OBSERVADA,

    BORRADOR_SUBIDO,
    BORRADOR_APROBADO,
    BORRADOR_RECHAZADO,

    ACTA_GENERADA,

    NOTIFICACION_GENERAL
}
